// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdma_read_addr.h"

extern XDma_read_addr_Config XDma_read_addr_ConfigTable[];

XDma_read_addr_Config *XDma_read_addr_LookupConfig(u16 DeviceId) {
	XDma_read_addr_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDMA_READ_ADDR_NUM_INSTANCES; Index++) {
		if (XDma_read_addr_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDma_read_addr_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDma_read_addr_Initialize(XDma_read_addr *InstancePtr, u16 DeviceId) {
	XDma_read_addr_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDma_read_addr_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDma_read_addr_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

