// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdma_read_addr.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDma_read_addr_CfgInitialize(XDma_read_addr *InstancePtr, XDma_read_addr_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDma_read_addr_Start(XDma_read_addr *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_AP_CTRL) & 0x80;
    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDma_read_addr_IsDone(XDma_read_addr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDma_read_addr_IsIdle(XDma_read_addr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDma_read_addr_IsReady(XDma_read_addr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDma_read_addr_EnableAutoRestart(XDma_read_addr *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XDma_read_addr_DisableAutoRestart(XDma_read_addr *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XDma_read_addr_Get_return(XDma_read_addr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XDma_read_addr_Set_frame_buffer0(XDma_read_addr *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_FRAME_BUFFER0_DATA, Data);
}

u32 XDma_read_addr_Get_frame_buffer0(XDma_read_addr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_FRAME_BUFFER0_DATA);
    return Data;
}

void XDma_read_addr_Set_frame_buffer1(XDma_read_addr *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_FRAME_BUFFER1_DATA, Data);
}

u32 XDma_read_addr_Get_frame_buffer1(XDma_read_addr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_FRAME_BUFFER1_DATA);
    return Data;
}

void XDma_read_addr_Set_frame_buffer2(XDma_read_addr *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_FRAME_BUFFER2_DATA, Data);
}

u32 XDma_read_addr_Get_frame_buffer2(XDma_read_addr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_FRAME_BUFFER2_DATA);
    return Data;
}

void XDma_read_addr_Set_mode_V(XDma_read_addr *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_MODE_V_DATA, Data);
}

u32 XDma_read_addr_Get_mode_V(XDma_read_addr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_MODE_V_DATA);
    return Data;
}

void XDma_read_addr_InterruptGlobalEnable(XDma_read_addr *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_GIE, 1);
}

void XDma_read_addr_InterruptGlobalDisable(XDma_read_addr *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_GIE, 0);
}

void XDma_read_addr_InterruptEnable(XDma_read_addr *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_IER);
    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_IER, Register | Mask);
}

void XDma_read_addr_InterruptDisable(XDma_read_addr *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_IER);
    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_IER, Register & (~Mask));
}

void XDma_read_addr_InterruptClear(XDma_read_addr *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDma_read_addr_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_ISR, Mask);
}

u32 XDma_read_addr_InterruptGetEnabled(XDma_read_addr *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_IER);
}

u32 XDma_read_addr_InterruptGetStatus(XDma_read_addr *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDma_read_addr_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_READ_ADDR_AXILITES_ADDR_ISR);
}

