// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// 0x18 : Data signal of frame_buffer0
//        bit 31~0 - frame_buffer0[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of frame_buffer1
//        bit 31~0 - frame_buffer1[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of frame_buffer2
//        bit 31~0 - frame_buffer2[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of mode_V
//        bit 0  - mode_V[0] (Read/Write)
//        others - reserved
// 0x34 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDMA_READ_ADDR_AXILITES_ADDR_AP_CTRL            0x00
#define XDMA_READ_ADDR_AXILITES_ADDR_GIE                0x04
#define XDMA_READ_ADDR_AXILITES_ADDR_IER                0x08
#define XDMA_READ_ADDR_AXILITES_ADDR_ISR                0x0c
#define XDMA_READ_ADDR_AXILITES_ADDR_AP_RETURN          0x10
#define XDMA_READ_ADDR_AXILITES_BITS_AP_RETURN          32
#define XDMA_READ_ADDR_AXILITES_ADDR_FRAME_BUFFER0_DATA 0x18
#define XDMA_READ_ADDR_AXILITES_BITS_FRAME_BUFFER0_DATA 32
#define XDMA_READ_ADDR_AXILITES_ADDR_FRAME_BUFFER1_DATA 0x20
#define XDMA_READ_ADDR_AXILITES_BITS_FRAME_BUFFER1_DATA 32
#define XDMA_READ_ADDR_AXILITES_ADDR_FRAME_BUFFER2_DATA 0x28
#define XDMA_READ_ADDR_AXILITES_BITS_FRAME_BUFFER2_DATA 32
#define XDMA_READ_ADDR_AXILITES_ADDR_MODE_V_DATA        0x30
#define XDMA_READ_ADDR_AXILITES_BITS_MODE_V_DATA        1

