// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XDMA_READ_ADDR_H
#define XDMA_READ_ADDR_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdma_read_addr_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XDma_read_addr_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XDma_read_addr;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDma_read_addr_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDma_read_addr_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDma_read_addr_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDma_read_addr_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDma_read_addr_Initialize(XDma_read_addr *InstancePtr, u16 DeviceId);
XDma_read_addr_Config* XDma_read_addr_LookupConfig(u16 DeviceId);
int XDma_read_addr_CfgInitialize(XDma_read_addr *InstancePtr, XDma_read_addr_Config *ConfigPtr);
#else
int XDma_read_addr_Initialize(XDma_read_addr *InstancePtr, const char* InstanceName);
int XDma_read_addr_Release(XDma_read_addr *InstancePtr);
#endif

void XDma_read_addr_Start(XDma_read_addr *InstancePtr);
u32 XDma_read_addr_IsDone(XDma_read_addr *InstancePtr);
u32 XDma_read_addr_IsIdle(XDma_read_addr *InstancePtr);
u32 XDma_read_addr_IsReady(XDma_read_addr *InstancePtr);
void XDma_read_addr_EnableAutoRestart(XDma_read_addr *InstancePtr);
void XDma_read_addr_DisableAutoRestart(XDma_read_addr *InstancePtr);
u32 XDma_read_addr_Get_return(XDma_read_addr *InstancePtr);

void XDma_read_addr_Set_frame_buffer0(XDma_read_addr *InstancePtr, u32 Data);
u32 XDma_read_addr_Get_frame_buffer0(XDma_read_addr *InstancePtr);
void XDma_read_addr_Set_frame_buffer1(XDma_read_addr *InstancePtr, u32 Data);
u32 XDma_read_addr_Get_frame_buffer1(XDma_read_addr *InstancePtr);
void XDma_read_addr_Set_frame_buffer2(XDma_read_addr *InstancePtr, u32 Data);
u32 XDma_read_addr_Get_frame_buffer2(XDma_read_addr *InstancePtr);
void XDma_read_addr_Set_mode_V(XDma_read_addr *InstancePtr, u32 Data);
u32 XDma_read_addr_Get_mode_V(XDma_read_addr *InstancePtr);

void XDma_read_addr_InterruptGlobalEnable(XDma_read_addr *InstancePtr);
void XDma_read_addr_InterruptGlobalDisable(XDma_read_addr *InstancePtr);
void XDma_read_addr_InterruptEnable(XDma_read_addr *InstancePtr, u32 Mask);
void XDma_read_addr_InterruptDisable(XDma_read_addr *InstancePtr, u32 Mask);
void XDma_read_addr_InterruptClear(XDma_read_addr *InstancePtr, u32 Mask);
u32 XDma_read_addr_InterruptGetEnabled(XDma_read_addr *InstancePtr);
u32 XDma_read_addr_InterruptGetStatus(XDma_read_addr *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
