:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2016.4
:: Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

E:/Xilinx/Vivado_HLS/2016.4/../../Vivado/2016.4/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z020clg400-1 ../xilinx_com_hls_DMA_Read_addr_1_0.zip
